p8105\_hw3\_dz2399
================
DZ
October 4, 2018

Problem 1
---------

#### First, do some data cleaning:

-   format the data to use appropriate variable names;
-   focus on the “Overall Health” topic
-   include only responses from “Excellent” to “Poor” (i.e. no pre-collapsed categories)
-   organize responses as a factor taking levels from “Excellent” to “Poor”

``` r
data("brfss_smart2010")
df_brfss <- brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic== 'Overall Health') %>%
  select(-c(class,topic,question,sample_size,confidence_limit_low:geo_location)) %>% 
  mutate(response= as.factor(response))
df_brfss$response <-
  factor(df_brfss$response,levels(df_brfss$response)[c(4,2,3,5,1)])
rm(brfss_smart2010)
```

#### In 2002, which states were observed at 7 locations?

``` r
df_brfss %>% 
  filter(year==2002) %>% 
  spread(key=response, value=data_value) %>% 
  group_by(locationabbr) %>% 
  mutate(locations = length(unique(locationdesc))) %>% 
  filter(locations == 7 ) %>% 
  distinct(locationabbr)
```

    ## # A tibble: 3 x 1
    ## # Groups:   locationabbr [3]
    ##   locationabbr
    ##   <chr>       
    ## 1 CT          
    ## 2 FL          
    ## 3 NC

-   In 2002, Connecticut, Florida and North Carolina were observed at 7 locations.

#### Make a “spaghetti plot” that shows the number of observations in each state from 2002 to 2010.

``` r
df_brfss %>% 
  group_by(locationabbr,year) %>% 
  summarise(n_obs = length(data_value)) %>% 
  filter(year==2002|year==2010) %>% 
  ggplot(aes(x=year, y=n_obs, color = locationabbr))+
  geom_line()+
  ggtitle('the number of observations in each state from 2002 to 2010')
```

![](p8105_hw3_dz2399_files/figure-markdown_github/unnamed-chunk-3-1.png)

#### Make a table showing, for the years 2002, 2006, and 2010, the mean and standard deviation of the proportion of “Excellent” responses across locations in NY State.

``` r
df_brfss %>% 
  spread(key=response, value=data_value) %>% 
  janitor::clean_names() %>% 
  filter(year==2002|year==2006|year==2010, locationabbr=='NY') %>% 
  group_by(year) %>% 
  summarise(mean=mean(excellent),
            sd=sd(excellent)) %>% 
  knitr::kable(digits = 1)
```

|  year|  mean|   sd|
|-----:|-----:|----:|
|  2002|  24.0|  4.5|
|  2006|  22.5|  4.0|
|  2010|  22.7|  3.6|

-   In 2002, the mean for "Excellent" response in across the New York state is 24 with the standard deviation of 4.5. In 2006, this mean is 22.5 with the standard deviation of 4.0. IN 2010, this mean is 22.7 with the standard deviation of 3.6.

#### Make a five-panel plot that shows, for each response category separately, the distribution of these state-level averages over time.

``` r
df_brfss %>% 
  group_by(year, locationabbr, response) %>% 
  summarise(state_mean=mean(data_value)) %>% 
  ggplot(aes(x=year,y=state_mean))+
  geom_point()+
  facet_grid(.~response)
```

    ## Warning: Removed 21 rows containing missing values (geom_point).

![](p8105_hw3_dz2399_files/figure-markdown_github/unnamed-chunk-5-1.png)

Problem 2
---------

#### The goal is to do some exploration of this dataset. To that end, write a short description of the dataset, noting the size and structure of the data, describing some key variables, and giving illstrative examples of observations.

``` r
data("instacart")
instacart <- instacart %>% 
  janitor::clean_names()
```

The dataset has the dimension of 1384617, 15. The order\_id and product\_is is a numeric variable that is the order identifier and the product identifier. The add\_to\_cart\_order is a numeric value that represents the order in which each product was added to cart.

#### How many aisles are there, and which aisles are the most items ordered from?

``` r
instacart %>% 
  distinct(aisle_id) %>% 
  nrow()
```

    ## [1] 134

``` r
instacart %>% 
  group_by(aisle) %>% 
  summarise(number_of_items = n()) %>% 
  arrange(desc(number_of_items)) %>% 
  slice(1)
```

    ## # A tibble: 1 x 2
    ##   aisle            number_of_items
    ##   <chr>                      <int>
    ## 1 fresh vegetables          150609

-   There are 134 distinct rows, and the fresh vegetables aisle has the most items ordered, 150609 items.

#### Make a plot that shows the number of items ordered in each aisle. Order aisles sensibly, and organize your plot so others can read it.

``` r
aisle_plot <- instacart %>% 
  group_by(aisle_id) %>% 
  summarise(number_of_items = n()) %>% 
  arrange(desc(number_of_items))
aisle_plot$aisle_id_group <- as.numeric(cut(aisle_plot$aisle_id,4))
  ggplot(aisle_plot,aes(x=factor(aisle_id),y=number_of_items))+
  geom_point() + 
  xlab("Aisle_ID") +
  facet_wrap(~aisle_id_group, ncol = 1, scales = "free_x")+
  ggtitle('The number of items ordered in each aisle.')
```

![](p8105_hw3_dz2399_files/figure-markdown_github/unnamed-chunk-8-1.png)

#### Make a table showing the most popular item aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”

``` r
instacart %>% 
  filter(aisle=='baking ingredients'|aisle== 'dog food care'|aisle== 'packaged vegetables fruits') %>% 
  group_by(aisle,product_name) %>% 
  summarise(num_of_purchase = n()) %>% 
  group_by(aisle) %>% 
  filter(num_of_purchase == max(num_of_purchase)) %>% 
  knitr::kable()
```

| aisle                          | product\_name                                    |                                                                                                                                                                                                                num\_of\_purchase|
|:-------------------------------|:-------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| baking ingredients             | Light Brown Sugar                                |                                                                                                                                                                                                                              499|
| dog food care                  | Snack Sticks Chicken & Rice Recipe Dog Treats    |                                                                                                                                                                                                                               30|
| packaged vegetables fruits     | Organic Baby Spinach                             |                                                                                                                                                                                                                             9784|
| \* The most popular items in b | aking ingredients is light brown sugar, purchase |  d 499 times. The most popular items in dog food care is Snack Sticks chicken and Rice recipe Dog Treats, purchased 30 times. The most popular item in packaged vagetables fruits is Organic Baby Spinich, purchased 9784 times.|

#### Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7 table)

``` r
instacart %>% 
  filter(product_name=='Pink Lady Apples'
         |product_name=='Coffee Ice Cream') %>% 
  select(order_dow,order_hour_of_day,product_name) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(mean_time= mean(order_hour_of_day)) %>% 
  spread(key=product_name, value=mean_time)
```

    ## # A tibble: 7 x 3
    ##   order_dow `Coffee Ice Cream` `Pink Lady Apples`
    ##       <int>              <dbl>              <dbl>
    ## 1         0               13.8               13.4
    ## 2         1               14.3               11.4
    ## 3         2               15.4               11.7
    ## 4         3               15.3               14.2
    ## 5         4               15.2               11.6
    ## 6         5               12.3               12.8
    ## 7         6               13.8               11.9

Problem 3
---------

``` r
data("ny_noaa")
df_nynoaa <- ny_noaa %>% 
  separate(date,into = c("year","month","day")) %>% 
  janitor::clean_names() %>% 
  mutate(tmin=as.numeric(tmin),
         tmax=as.numeric(tmax)) %>% 
  na.omit()
```

#### Do some data cleaning. Create separate variables for year, month, and day. Ensure observations for temperature, precipitation, and snowfall are given in reasonable units. For snowfall, what are the most commonly observed values? Why?

``` r
df_nynoaa %>% 
  group_by(snow) %>% 
  summarise(obs=n()) %>% 
  filter(obs==max(obs))
```

    ## # A tibble: 1 x 2
    ##    snow     obs
    ##   <int>   <int>
    ## 1     0 1112758

-   The most commonly observed value for snowfall is 0, since in New York it only snows for a couple of times in winter, other times the snowfall would be zero.

#### Make a two-panel plot showing the average temperature in January and in July in each station across years. Is there any observable / interpretable structure? Any outliers?

``` r
df_nynoaa %>% 
  filter(month=='01'|month=='06') %>%
  group_by(month,year) %>% 
  summarise(month_mean=mean(tmax)) %>%
  ggplot(aes(x=factor(month),y=month_mean))+
    geom_boxplot()+
  ggtitle('The average temperature in January and in July in each station across years')
```

![](p8105_hw3_dz2399_files/figure-markdown_github/unnamed-chunk-12-1.png)

#### Make a two-panel plot showing (i) tmax vs tmin for the full dataset (note that a scatterplot may not be the best option); and (ii) make a plot showing the distribution of snowfall values greater than 0 and less than 100 separately by year.

``` r
plot1 <- ggplot(data=df_nynoaa, aes(x=tmax,y=tmin))+
  geom_hex()+
  ggtitle('tmax vs tmin for the full dataset')+
  theme(legend.position = "right")

# plot2 <- df_nynoaa %>%
#   filter(snow>0) %>%
#   ggplot(aes(x=year, y=snow))+
#   geom_density()
# 
# plot3 <-  df_nynoaa %>%
#   filter(snow<100) %>%
#   ggplot(aes(x=year, y=snow))+
#   geom_point()+
#   theme(legend.position = "none")
# 
# plot1/(plot2+plot3)
```
