---
title: "p8105_hw3_dz2399"
author: "DZ"
date: "October 4, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)
```


## Problem 1
### First, do some data cleaning:

* format the data to use appropriate variable names;
* focus on the “Overall Health” topic
* include only responses from “Excellent” to “Poor” (i.e. no pre-collapsed categories)
* organize responses as a factor taking levels from “Excellent” to “Poor”
```{r}
data("brfss_smart2010")
df_brfss <- brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic== 'Overall Health') %>%
  select(-c(class,topic,question,sample_size,confidence_limit_low:geo_location)) %>%
  mutate(response = as.factor(response))
```

#### In 2002, which states were observed at 7 locations?
```{r}
df_brfss %>% 
  filter(year==2002) %>% 
  spread(key=response, value=data_value) %>% 
  group_by(locationabbr) %>% 
  mutate(locations = length(unique(locationdesc))) %>% 
  filter(locations == 7 ) %>% 
  distinct(locationabbr)

df_brfss %>% 
  filter(year==2002) %>%
  unique(locationdesc)
  
```

